"""Add dual mode support (hours and times)

Revision ID: 015d569fc6f6
Revises: 11c042b3421a
Create Date: 2025-11-08 04:35:05.887943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015d569fc6f6'
down_revision: Union[str, Sequence[str], None] = '11c042b3421a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add time_entry_mode to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_entry_mode', sa.String(length=10), nullable=False, server_default='hours'))

    # Add time-based fields to worktimes table
    with op.batch_alter_table('worktimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('break_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('worked_hours', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove time-based fields from worktimes table
    with op.batch_alter_table('worktimes', schema=None) as batch_op:
        batch_op.alter_column('worked_hours', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('break_minutes')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # Remove time_entry_mode from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('time_entry_mode')
    # ### end Alembic commands ###
