"""Add Regie fields to Worktime model

Revision ID: 11c042b3421a
Revises: 9ddb3fd6e84f
Create Date: 2025-11-06 13:43:53.721262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c042b3421a'
down_revision: Union[str, Sequence[str], None] = '9ddb3fd6e84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Regie-related columns to worktimes table
    with op.batch_alter_table('worktimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_regie', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('materials_used', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('picture_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worktimes', schema=None) as batch_op:
        batch_op.drop_column('picture_path')
        batch_op.drop_column('materials_used')
        batch_op.drop_column('is_regie')
    # ### end Alembic commands ###
