"""Add admin interface schema extensions

Revision ID: 9ddb3fd6e84f
Revises: 5b977613b3ad
Create Date: 2025-11-06 12:46:06.622916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddb3fd6e84f'
down_revision: Union[str, Sequence[str], None] = '5b977613b3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_days_date'), 'special_days', ['date'], unique=False)
    op.create_index(op.f('ix_special_days_id'), 'special_days', ['id'], unique=False)
    op.create_index(op.f('ix_special_days_user_id'), 'special_days', ['user_id'], unique=False)
    op.create_table('baustelle_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baustelle_id', sa.Integer(), nullable=False),
    sa.Column('employee_type', sa.String(length=20), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baustelle_id'], ['baustellen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baustelle_rates_id'), 'baustelle_rates', ['id'], unique=False)

    # For SQLite, add columns directly without FK constraint (SQLite doesn't enforce FKs by default)
    # The FK constraint exists in the model but won't be enforced at the database level
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employee_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop columns added to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('employee_type')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_index(op.f('ix_baustelle_rates_id'), table_name='baustelle_rates')
    op.drop_table('baustelle_rates')
    op.drop_index(op.f('ix_special_days_user_id'), table_name='special_days')
    op.drop_index(op.f('ix_special_days_id'), table_name='special_days')
    op.drop_index(op.f('ix_special_days_date'), table_name='special_days')
    op.drop_table('special_days')
    # ### end Alembic commands ###
